apiVersion: apps/v1
kind: Deployment
metadata:
  name: flower-app-deployment
spec: # it define behavior of the deployment
  replicas: 2
  selector:
    matchLabels:
      app: web
  template: # it define the pod template
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: flower-container
        image: imranwork/sre-test-image:1.0
        resources:
          limits:
            memory: "500Mi"
            cpu: "300m"
          requests:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 3015
---
apiVersion: v1
kind: Service
metadata:
  name: flower-app-service
spec:
  selector:
    app: web
  ports:
  - port: 3017 # this is the port that will be exposed
    targetPort: 3015 # this is the port that the container is listening on
    protocol: TCP
  type: LoadBalancer # this will expose the service on a random port on each node
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: flower-app-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flower-app-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 2


